
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target '___PACKAGENAME___' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ___PACKAGENAME___

  # Networking
  pod 'Moya/RxSwift'

  # Security
  pod 'KeychainSwift'

  # UI
  pod 'IQKeyboardManager'
  pod 'Kingfisher', '~> 4.10.0'
  pod 'MBProgressHUD'
  pod 'PopupDialog'
  pod 'RxCocoa'
  pod 'SnapKit'
  
end